### ISSUE TITLE
[Request] Add to F-Droid and izzyondroid

### ISSUE THREAD

**Issue by Moxville** [bmaroti9/Overmorrow#3]
Thank you for the very nice app. Looks simple and neat.

Would be very nice to see your App in F-Droid and izzyondroid :)

https://f-droid.org/
https://f-droid.org/docs/

https://apt.izzysoft.de/fdroid/index/info
https://apt.izzysoft.de/fdroid/index.php
https://github.com/IzzySoft

**Comment by bmaroti9** [comment]
Hi!
Sorry for the long delay. I have added Overmorrow to Izzydroid. 🎉
Adding to F-droid looks a lot more complicated and I really don't think i'ts necessary because it's already on IzzyOnDroid.
If there will be more interest in adding to F-droid specifically then i will consider adding it but for now i am closing this issue as completed.
Cheers, Balint

**Comment by offa** [comment]
While Izzys repo is great, the official repo is the default and would make access much easier.
If you do not object, I would try to submitted related build metadata.
