### ISSUE TITLE
Please add Met Norway as weather provider

### ISSUE THREAD

**Issue by serrq** [bmaroti9/Overmorrow#33]
https://api.met.no/

https://www.met.no/en

https://api.met.no/doc/support

**Comment by bmaroti9** [comment]
how about keeping it like this and just letting the air quality data be from open-meteo?

![image](https://github.com/user-attachments/assets/b3e2d530-bee2-4867-b828-ae9b1eede7e9)

because if we do it in the way you said then it would make the radar appear which would look kind of ugly. 

![image](https://github.com/user-attachments/assets/a1e1d197-11f7-4f16-910b-f4b6ca62af4e)

**Comment by bmaroti9** [comment]
I'm not going to write to them. This is not as simple as just writing some code. They would need to set up tons of measuring stations, to get the data, and they are not going to do that just because I asked them. 
But you can ask them yourself...
Till then it's gonna stay like this.

**Comment by skdubg** [comment]
i think it doesnt work:
![Screenshot_20240928-172758](https://github.com/user-attachments/assets/09ec10e1-4714-4f9a-83c6-d0c3a9ebcedd)

**Comment by bmaroti9** [comment]
That is the search provider not the weather provider. You can set the weather provider at the end of the forecast. it's confusing because both open meteo and weatherapi offer geocoding for free, so that's the two I use instead of using a separate geocoding api

**Comment by skdubg** [comment]
Oh i didnt see it 😂

thanks...it works now
