### ISSUE TITLE
Allergens widget

### ISSUE THREAD

**Issue by Wendigogo** [bmaroti9/Overmorrow#37]
Hi,
I just discovered your app throught f-droid and it is really great.

Do you plan to add allergens information at some point? It's the only missing thing in you app for me.

Thanks for your great work anyway.

**Comment by bmaroti9** [comment]
Hi! I like the idea of the allergens widget. However once again i'm struggling to decide on the ui part of it.
It could be made part of air-quality, but then either the air quality widget would have to be bigger and  it would be half cut off by the end of the screen, when opening the app, and i don't think that would look good. Another option is to have like an expand more button, that would show more detail to the air quality including the allergens information. This could go in two ways: 1. expand to another page, 2. expand like the daily list does, to more info. I personally am not a huge fan of expanding to another page, and overmorrow has always had all the info on one page only. The second option could work though.
Another idea is to add it in a separate widget. I have already thought about doing this, not with just the allergens, but with moon phase, and visibility, which Overmorrow lacks, and other apps have. But this introduces new questions. Where would these new widgets be placed? I don't want to add any other stuff in front of the forecast because then you would have to scroll too much to get there. i thought of adding it after the 3 day forecast and before the daily, but i'm not sure about that.
Anyway i'm sorry to bother you with all these details, i'm just trying to tell you that this is the reason i haven't done anything about it yet. Also if you or anyone have any ideas then please share them!
Also i would like to mention that only open-meteo has allergens data and neither weatherapi, or met-norway have them,
so it will probably be an open-meteo only feature.

**Comment by Wendigogo** [comment]
Hi,

Thanks for the detailed answer, it's really appreciated.

I also think Overmorrow will be to high to be really usable. Maybe it already is...
And I'm not a huge fan of expandable stuff or opening new page for each widget.

So I have some ideas I would share :

A  lateral slide to show other information, like in forecast. But it's a workaround and it needs a way to be shown to user that there is more on side.

A setting to only show desired widgets (or hide others). Some widgets should not be useful for everyone: Allergens for example or in my case Radar. We should also add or remove (hide) some widgets depending on location, season or whatever.

An alternative would be to have a compact mode for user selected widgets (title only). So everything is present but unuseful information (relative to any user) doesn't eat too much space on screen. With the ability to expand/collapse each widget independently on the go.

It's my second concern about Overmorrow : I really would like to personalize, not only widget position but also widget presence.

**Comment by bmaroti9** [comment]
You are talking about adding these, right?

![image](https://github.com/user-attachments/assets/c126659b-c5c4-498f-8be7-0c554ac49e8f)

**Comment by Wendigogo** [comment]
Yes, i talked about pollens. And those I personnally follow are on your list. 😉

Thanks.

**Comment by bmaroti9** [comment]
Just noticed, there is a problem. Open-meteo only has this data for Europe. 
![image](https://github.com/user-attachments/assets/7791a76b-f284-405f-be37-cf7d151ead5d)
Not sure what to do now. it kind of seems pointless only for europe... 
Neither weatherapi or met-norway has this data. Maybe i'll look around for any other apis but my hopes aren't high as almost all of them are paid.

**Comment by Wendigogo** [comment]
I live in Europe so its not pointless to everyone. 😉

I guess that with ability to hide some widgets this can be integrated and updated if other countries add these informations at some point.

Anyway, it's your app and you can do whatever you want.

Here is a large compatibility list of sources, api and given informations : https://github.com/breezy-weather/breezy-weather/blob/main/docs/SOURCES.md

Maybe that could be useful for you.

**Comment by bmaroti9** [comment]
So i looked into the breezy-weather docs, but it unfortunately it didn't help. The only 2 providers they listed with pollen are open-meteo and AccuWeather. Open-meteo as i said before only has pollen for europe. As for AccuWeather, they are a totally paid service, i have no idea how breezy managed to get an api key from them for free...
I also looked through the web for a free pollen api, but no luck. Basically all of them are ridiculously low call amount per day (about 50), or just a free trial that ends after a week. So it seems like it will be a europe only feature.

**Comment by bmaroti9** [comment]
Hi!
So here is what i came up with:

https://github.com/user-attachments/assets/3731a72d-594b-48b6-b9b1-4a0b550979af

I decided on the totally separate air quality page option. Since i was making it a totally separate page, it would've looked akward if there was nothing else, so i used the occasion and made a bunch of extra data displays as well.

**Comment by Wendigogo** [comment]
That's a great improvement! This new page is really nice with a lot of clear and useful information about air quality!

**Comment by bmaroti9** [comment]
available in v2.4.3
