### ISSUE TITLE
Weather wrong because of location

### ISSUE THREAD

**Issue by HydroIgnite** [bmaroti9/Overmorrow#44]
My dad said it was raining and windy outside so he came in the house but when I checked inside of overmorrow, It said it was a cloudy night and maybe y'all can fix this?
![Screenshot_20241111_173632](https://github.com/user-attachments/assets/f5c513ca-3c7c-41a5-b632-94f8e29e8a39)

**Comment by bmaroti9** [comment]
Hi!
So Overmorrow, like all other foss weather apps, doesn't actually generate the weather data itself, instead it relies on 3rd party weather providers. If the data is unaccurate, you could try to switch to one of the other weather providers (currently there are 3) and see if that one is better. I'm just displaying the data these weather providers send, and can't do anything about their inaccuracy.
You also mentioned "because of location", i'm not sure if you mean it's displaying the wrong city or something, but actually the weather data is fetched to your coordinates, not to the place it says on top. So even if the city it says on the top is unaccurate, your weather data will not be affected by it because, it fetches to your longitude latitude.
Hope this helps,
Balint
