### ISSUE TITLE
Offline Mode

### ISSUE THREAD

**Issue by RealVegOs** [bmaroti9/Overmorrow#45]
Feature request! Some folks might want data caching for offline mode. There are not that many weather apps of that kind. I use a WiFi tablet as GPS navigation. It would be nice, to have your weather app on my hikes with me. That's my suggestion. Thanks for any consideration. 

PS: Data caching should be persistent, even if you turn your device off. I alway do and boot my tab when I leave the train to my routes.

**Comment by bmaroti9** [comment]
Hi! Cool idea, Always wanted to implement it, but it's nice to have a separate issue for it.

**Comment by bmaroti9** [comment]
Ok, so i started working on it, but a few thing need to be addressed:
- the images: currently the default is network images, but these are fetched for the current condition, and if the weather condition changes, and your offline, than the best i think is to fall back to the asset images.
- the pressure: of the top 4 displayed weather data (in the  top circles) all of them are fetched hourly, except the humidity. I could fetch the humidity hourly as well, but i don't know if it's worth it just for the possibility of offline usage. An alternative would be to just display the current of the last fetch, but that could be unaccurate.
- air quality: basically the same applies for air quality, as for the humidity. I don't fetch hourly data for any of these, except when you actually open the page (I do this to reduce the amount of useless api calls). 
- the radar: the radar images get outdated pretty quickly (30 minutes) and while i could save it for a while, it would be totally pointless to keep it for long. so i was just thinking of disabling it for offline.

The forecast is not a problem, because every data is fetched for hourly, so i can just get rid of the past data, and show the rest as usual. 

Of course i could solve both the humidity and air quality, by just fetching every piece of information in hourly not just for current. But I'm not sure that would be ideal, because that would mean a lot more data being fetched, longer loading times, bigger chance of getting rate limited, and so on. So basically we have to consider if these are important enough to fetch them hourly, or just display the last known data.

**Comment by RealVegOs** [comment]
I tend to suggest last known data, because it is on the users duty to fetch data before going offline. I always have to load new routes for my navigation before I leave the house. So I also can have a look on the weather which will fetch current data. Or is your app alway running in the background?

**Comment by bmaroti9** [comment]
No, of course it's not running in the background. I was just talking about the fact that if for example you have hourly data, instead of current data for something, then say if that changes during the day, then when you open the app again but now offline it will show you the data that was predicted when you last opened it, instead of the data that was currently when you last opened it. this is what is going to be implemented for temperature, rain... ect. The only exceptions are humidity, and air quality, for which this can't be done, because the data being fetched is not a list of numbers for each hour, instead it's just one number for current. That's why i was asking about making these be fetched in hourly format as well. 
But since you said, the last known data is fine, then that's good too. 👍

**Comment by bmaroti9** [comment]
available in v2.4.4!
I spent a lot of time troubleshooting all kinds of bugs, I think i managed to track most of them down, but it might be possible that some might remain.
